name: Build and Deploy to Render

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to DockerHub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t v1 .

      # Push the Docker image to DockerHub
      - name: Push Docker image
        run: |
          docker tag v1 username/v1:latest
          docker push username/v1:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Trigger Render deploy for the full-stack Flask app (Frontend + Backend)
      - name: Trigger Render Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_HOOK }}
